version: 1.0.{build}
configuration:
  - Debug
  - Release
environment:
  WORKSPACEROOT: test\DotNet.Globals.Core.Tests
build_script:
  - echo "Building for %CONFIGURATION%"
test_script:
  - ps: .\build.ps1 %CONFIGURATION%
cache:
  - '%USERPROFILE%\.nuget\packages'
